#!/usr/bin/env bash
# diskos-ota-push.sh - sign a custom mq_ui binary and stage it on the device as a permanent update over Wi-Fi.
#
# Usage:
#   DISKOS_IP=<ip> DISKOS_PW=<pw> ./tools/diskos-ota-push.sh [path/to/mq_ui] [--epoch N] [--reboot]
#
# Requires:
#   - signing/root_priv.pem and signing/leaf_priv.pem (generated by ./tools/diskos-ota-keygen.sh)
#   - openssl, ssh, scp, sha256sum
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SIGN_DIR="$REPO_ROOT/signing"

BIN=""
EPOCH=""
REBOOT=0
PERMANENT=0

while [ $# -gt 0 ]; do
    case "$1" in
        --epoch)
            EPOCH="$2"
            shift 2
            ;;
        --reboot)
            REBOOT=1
            shift
            ;;
        --permanent)
            PERMANENT=1
            shift
            ;;
        --trial)
            PERMANENT=0
            shift
            ;;
        -*)
            echo "Unknown option: $1" >&2
            echo "Usage: DISKOS_IP=<ip> DISKOS_PW=<pw> $0 [path/to/mq_ui] [--epoch N] [--reboot] [--permanent]" >&2
            exit 1
            ;;
        *)
            if [ -z "$BIN" ]; then
                BIN="$1"
            fi
            shift
            ;;
    esac
done

if [ -z "$BIN" ]; then
    if [ -f "$REPO_ROOT/ui/mq_ui" ]; then
        BIN="$REPO_ROOT/ui/mq_ui"
    elif [ -f "./mq_ui" ]; then
        BIN="./mq_ui"
    else
        echo "ERROR: mq_ui binary not found. Build it in ui/ or specify path." >&2
        exit 1
    fi
fi

if [ ! -f "$BIN" ]; then
    echo "ERROR: binary not found: $BIN" >&2
    exit 1
fi

if [ ! -f "$SIGN_DIR/root_priv.pem" ] || [ ! -f "$SIGN_DIR/leaf_priv.pem" ]; then
    echo "ERROR: Signing keys not found in $SIGN_DIR." >&2
    echo "Run ./tools/diskos-ota-keygen.sh first to generate your keys." >&2
    exit 1
fi

IP="${DISKOS_IP:?set DISKOS_IP to device IP (shown in Settings > System > Debug Mode)}"
PW="${DISKOS_PW:-}"

# Manage persistent epoch counter
EPOCH_FILE="$SIGN_DIR/.epoch"
if [ -z "$EPOCH" ]; then
    if [ -f "$EPOCH_FILE" ]; then
        CUR_EPOCH=$(cat "$EPOCH_FILE" 2>/dev/null || echo 0)
        EPOCH=$((CUR_EPOCH + 1))
    else
        EPOCH=1
    fi
fi
echo "$EPOCH" > "$EPOCH_FILE"

VERSION="custom-ep${EPOCH}"
TMP_BUNDLE="$(mktemp -d "/tmp/diskos-bundle.XXXXXX")"
trap 'rm -rf "$TMP_BUNDLE"' EXIT

echo ">> Preparing signed bundle for $BIN (epoch $EPOCH, version $VERSION)..."

cp "$SIGN_DIR/leaf_pub.pem" "$TMP_BUNDLE/leafpub.pem"
LEAF_HASH=$(sha256sum "$TMP_BUNDLE/leafpub.pem" | cut -d' ' -f1)
UI_HASH=$(sha256sum "$BIN" | cut -d' ' -f1)
UI_SIZE=$(wc -c < "$BIN" | tr -d ' ')

# 1. keyauthz: authorized by root key
cat <<EOF > "$TMP_BUNDLE/keyauthz"
diskos-keyauthz-v1
keyid=developer-key
keyepoch=1
role=tier-a
pubkey_sha256=$LEAF_HASH
EOF
openssl dgst -sha256 -sign "$SIGN_DIR/root_priv.pem" -out "$TMP_BUNDLE/keyauthz.sig" "$TMP_BUNDLE/keyauthz"

# 2. update.manifest: authorized by leaf key
cat <<EOF > "$TMP_BUNDLE/update.manifest"
diskos-update-v1
component=mq_ui
epoch=$EPOCH
version=$VERSION
size=$UI_SIZE
sha256=$UI_HASH
channel=dev
EOF
openssl dgst -sha256 -sign "$SIGN_DIR/leaf_priv.pem" -out "$TMP_BUNDLE/update.manifest.sig" "$TMP_BUNDLE/update.manifest"

# Preflight: test with diskos-verify.sh locally
if [ -f "$REPO_ROOT/payload/diskos-verify.sh" ]; then
    echo ">> Running local cryptographic preflight check..."
    if ! /bin/sh "$REPO_ROOT/payload/diskos-verify.sh" "$SIGN_DIR/root_pub.pem" 1 1 "$TMP_BUNDLE" "$BIN" >/dev/null 2>&1; then
        echo "ERROR: Local verification check failed! Aborting." >&2
        exit 1
    fi
    echo "   Local verification check: OK"
fi

# Copy binary into bundle
cp "$BIN" "$TMP_BUNDLE/mq_ui"
chmod 755 "$TMP_BUNDLE/mq_ui"

# Package bundle into a single archive file on disk (avoiding pipe hangs with sshpass)
TAR_FILE="$TMP_BUNDLE/bundle.tar"
tar -C "$TMP_BUNDLE" -cf "$TAR_FILE" keyauthz keyauthz.sig leafpub.pem update.manifest update.manifest.sig mq_ui
TAR_SIZE="$(wc -c < "$TAR_FILE" | tr -d ' ')"
TAR_SIZE_MB="$(awk -v s="$TAR_SIZE" 'BEGIN { printf "%.2f", s / 1048576 }')"

# SSH setup - matching tools/diskos-deploy.sh convention
export SSHPASS="${PW:?set DISKOS_PW to the Debug Mode SSH password}"
SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=8 -o LogLevel=ERROR)
if command -v sshpass >/dev/null 2>&1; then
    SSH_CMD=(sshpass -e ssh "${SSH_OPTS[@]}")
else
    SSH_CMD=(ssh "${SSH_OPTS[@]}")
fi

stream_with_progress() {
    local file="$1"
    local size="$2"
    if command -v pv >/dev/null 2>&1; then
        pv -N "   Upload" -p -t -e -r -b -s "$size" "$file"
        return
    fi

    if command -v python3 >/dev/null 2>&1; then
        python3 -c '
import sys, time, os
path = sys.argv[1]
size = int(sys.argv[2])
sent = 0
chunk = 65536
t0 = time.time()
with open(path, "rb") as f:
    while True:
        buf = f.read(chunk)
        if not buf:
            break
        sys.stdout.buffer.write(buf)
        sent += len(buf)
        now = time.time()
        elapsed = max(now - t0, 0.001)
        speed = sent / elapsed
        pct = (sent / size) * 100 if size else 100
        mb_sent = sent / 1048576
        mb_tot = size / 1048576
        bar_len = 25
        filled = int(bar_len * sent / size) if size else bar_len
        bar = "=" * filled + (">" if filled < bar_len else "=") + " " * max(0, bar_len - filled - 1)
        sys.stderr.write(f"\r   Upload: [{bar[:bar_len]}] {pct:5.1f}% {mb_sent:4.1f}/{mb_tot:4.1f}MB ({speed/1048576:.2f}MB/s)")
        sys.stderr.flush()
sys.stderr.write("\n")
' "$file" "$size"
        return
    fi

    cat "$file"
}

if [ "$PERMANENT" -eq 1 ]; then
    TARGET_DIR="/usr/data/updates/good.incoming"
    echo ">> Uploading signed bundle (${TAR_SIZE_MB} MB) to root@$IP (direct permanent mode)..."
    stream_with_progress "$TAR_FILE" "$TAR_SIZE" | "${SSH_CMD[@]}" "root@$IP" \
        "mkdir -p $TARGET_DIR && rm -rf $TARGET_DIR/* && cd $TARGET_DIR && tar -xf -"
else
    TARGET_DIR="/usr/data/updates/pending"
    echo ">> Uploading signed bundle (${TAR_SIZE_MB} MB) to root@$IP (trial safety net mode)..."
    stream_with_progress "$TAR_FILE" "$TAR_SIZE" | "${SSH_CMD[@]}" "root@$IP" \
        "mkdir -p $TARGET_DIR && rm -f $TARGET_DIR/ready && cd $TARGET_DIR && tar -xf -"
fi
echo "   Bundle uploaded and extracted on device."

# Verify SHA256 of uploaded binary on device
echo ">> Verifying remote integrity (SHA-256)..."
REMOTE_SHA="$("${SSH_CMD[@]}" "root@$IP" "sha256sum $TARGET_DIR/mq_ui 2>/dev/null | cut -d' ' -f1")"
REMOTE_SHA="$(echo "$REMOTE_SHA" | tr -d '\r\n ')"
if [ "$REMOTE_SHA" != "$UI_HASH" ]; then
    echo "ERROR: Uploaded binary SHA-256 mismatch (local=$UI_HASH, remote=$REMOTE_SHA)!" >&2
    exit 1
fi
echo "   Remote integrity check: OK ($REMOTE_SHA)"

# Arm update
echo ">> Arming update on device..."
if [ "$PERMANENT" -eq 1 ]; then
    "${SSH_CMD[@]}" "root@$IP" "
        # Unblacklist this hash if it was previously rolled back
        [ -f /usr/data/updates/rejected ] && sed -i '/$UI_HASH/d' /usr/data/updates/rejected 2>/dev/null || true
        # Rotate good to good.prev and move incoming to good
        rm -rf /usr/data/updates/good.prev 2>/dev/null || true
        [ -d /usr/data/updates/good ] && mv /usr/data/updates/good /usr/data/updates/good.prev 2>/dev/null || true
        mv /usr/data/updates/good.incoming /usr/data/updates/good
        # Clean up any stale trial or pending state
        rm -rf /usr/data/updates/pending /usr/data/updates/active 2>/dev/null || true
        rm -f /usr/data/updates/trial* /usr/data/updates/healthy /usr/data/updates/rollback 2>/dev/null || true
        # Update accepted anti-rollback floor
        printf 'version=%s\nepoch=%s\n' '$VERSION' '$EPOCH' > /usr/data/updates/accepted.tmp \
            && mv -f /usr/data/updates/accepted.tmp /usr/data/updates/accepted
        touch /usr/data/updates/good/ready 2>/dev/null || true
        sync
    "
    echo "   Permanent update armed in /usr/data/updates/good."
    echo ""
    echo "=== Permanent update staged successfully! ==="
    echo "The update will be verified and installed automatically on the next boot."
else
    "${SSH_CMD[@]}" "root@$IP" "
        # Unblacklist this hash if it was previously rolled back
        [ -f /usr/data/updates/rejected ] && sed -i '/$UI_HASH/d' /usr/data/updates/rejected 2>/dev/null || true
        touch /usr/data/updates/pending/ready
        sync
    "
    echo "   Trial update armed (/usr/data/updates/pending/ready written)."
    echo ""
    echo "=== Trial update staged successfully! ==="
    echo "The update will boot with trial safety net on the next boot."
fi

if [ "$REBOOT" -eq 1 ]; then
    echo ">> Rebooting device now..."
    "${SSH_CMD[@]}" "root@$IP" "reboot" || true
else
    echo "To activate now, reboot the device:"
    echo "  ssh root@$IP reboot"
    echo "or pass --reboot to this script."
fi
