#!/usr/bin/env python3
"""Generate the Source Han / Noto Sans CJK supplement without modifying vendored LVGL.

Usage: python3 tools/generate_cjk_supplement.py [/path/to/font.otf]
Requires lv_font_conv (via npx or in node_modules).
The input font must be SIL OFL-licensed (e.g. Noto Sans CJK JP / Source Han Sans).
"""
import argparse
from pathlib import Path
import re
import shutil
import subprocess

app = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument('font', type=Path, nargs='?', default=None)
p.add_argument('--converter', type=Path, default=None)
a = p.parse_args()

font_path = a.font
if not font_path:
    # Try /tmp/NotoSansCJK-JP.otf or extract from system TTC
    cached = Path('/tmp/NotoSansCJK-JP.otf')
    if cached.exists():
        font_path = cached
    else:
        system_ttc = Path('/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc')
        if system_ttc.exists():
            from fontTools.ttLib import TTCollection
            ttc = TTCollection(str(system_ttc))
            ttc.fonts[0].save(str(cached))
            font_path = cached
        else:
            raise SystemExit('Please specify path to Source Han Sans / Noto Sans CJK font.')

converter_cmd = []
if a.converter and a.converter.exists():
    converter_cmd = ['node', str(a.converter)]
elif (app.parent/'node_modules/lv_font_conv/lv_font_conv.js').exists():
    converter_cmd = ['node', str(app.parent/'node_modules/lv_font_conv/lv_font_conv.js')]
elif shutil.which('lv_font_conv'):
    converter_cmd = ['lv_font_conv']
else:
    converter_cmd = ['npx', '-y', 'lv_font_conv']

chars = ''.join(line.strip() for line in (app/'fonts/cjk-supplement.txt').read_text().splitlines()
                if line.strip() and not line.lstrip().startswith('#'))
out = app/'font_cjk_extra_16.c'

cmd = [*converter_cmd, '--font', str(font_path), '--symbols', ''.join(sorted(set(chars))),
       '--size', '16', '--bpp', '4', '--no-compress', '--no-prefilter',
       '--format', 'lvgl', '--force-fast-kern-format',
       '--lv-font-name', 'font_cjk_extra_16', '-o', str(out)]
subprocess.run(cmd, check=True)

s = out.read_text()
s = re.sub(r' \* Opts:.*\n', ' * Generated by tools/generate_cjk_supplement.py from fonts/cjk-supplement.txt.\n', s)
s = '/* SPDX-License-Identifier: OFL-1.1 */\n/* Source Han Sans / Noto Sans CJK. Copyright 2014-2021 Adobe Systems Incorporated / Google LLC, with Reserved Font Name Source/Noto. */\n' + s
out.write_text(s)
print(f"Generated {out} ({len(set(chars))} glyphs)")
